name = input("Enter your name: ")
headline = input("Enter a short headline: ")
bio = input("Enter a bio: ")
email = input("Enter your valid email: ")
phone = int(input("Enter your mobile number: "))
address = input("Enter your address: ")
photo = input("Enter path or URL of your photo: ")


print("******Resume************")
print(name)
print(headline)
print(bio)
print(email)
print(phone)
print(address)
print(photo)
